name: Analysis-of-Endpoint-Connections

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/main/java/**'
      - 'src/main/webapp/**'

jobs:
  show-modified-files:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of modified files
        run: |
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD > modified_files.txt

      # Analyze the client sided REST-API calls
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm packages
        run: |
          cd supporting_scripts/analysis-of-endpoint-connections/src/main/typeScript/
          npm install
          npm install esm
          npm install --save-dev @types/node
          npm install --save typescript undici-types

      - name: Install and compile TypeScript
        run: |
          npm install -g typescript
          tsc -p supporting_scripts/analysis-of-endpoint-connections/src/main/typeScript/tsconfig.analysisOfEndpointConnections.json

      - name: Run analysis-of-endpoint-connections-client
        run: |
          node -r esm supporting_scripts/analysis-of-endpoint-connections/src/main/typeScript/AnalysisOfEndpointConnectionsClient.js $(cat modified_files.txt)

      # Analyze the server sided endpoints
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build analysis-of-endpoint-connections-server
        run: |
         ./gradlew :supporting_scripts:analysis-of-endpoint-connections:build
         ./gradlew :supporting_scripts:analysis-of-endpoint-connections:shadowJar

      - name: run analysis-of-endpoint-connections
        run: |
          java -jar supporting_scripts/analysis-of-endpoint-connections/build/libs/analysis-of-endpoint-connections-1.0-SNAPSHOT-all.jar $(cat modified_files.txt)
